/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyAvatar {
        "image": string;
    }
}
export interface MyAvatarCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMyAvatarElement;
}
declare global {
    interface HTMLMyAvatarElement extends Components.MyAvatar, HTMLStencilElement {
    }
    var HTMLMyAvatarElement: {
        prototype: HTMLMyAvatarElement;
        new (): HTMLMyAvatarElement;
    };
    interface HTMLElementTagNameMap {
        "my-avatar": HTMLMyAvatarElement;
    }
}
declare namespace LocalJSX {
    interface MyAvatar {
        "image"?: string;
        "onMyChange"?: (event: MyAvatarCustomEvent<String>) => void;
    }
    interface IntrinsicElements {
        "my-avatar": MyAvatar;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-avatar": LocalJSX.MyAvatar & JSXBase.HTMLAttributes<HTMLMyAvatarElement>;
        }
    }
}
